import { Question } from './types';

export const CHECKUP_QUESTIONS: Question[] = [
  {
    id: 'q1_mood',
    dimension: 'mood',
    aggregateDimension: 'emotional_wellbeing',
    categoryName: 'Emotional Well-Being',
    title: 'How have you been feeling emotionally over the past two weeks?',
    description: 'Reflect on your general emotional tone, moments of contentment, and fluctuations.',
    reverseScored: false,
    options: [
      { id: 'm1', label: 'Consistently low or heavy', sublabel: 'Struggling to feel upbeat or engaged', scoreValue: 1 },
      { id: 'm2', label: 'More down than usual', sublabel: 'Brief lighter moments, but mostly subdued', scoreValue: 2 },
      { id: 'm3', label: 'Evenly balanced', sublabel: 'A natural mix of ordinary ups and downs', scoreValue: 3 },
      { id: 'm4', label: 'Generally positive and steady', sublabel: 'Feeling mostly content and calm', scoreValue: 4 },
      { id: 'm5', label: 'Joyful, grounded, and fulfilled', sublabel: 'Strong sense of warmth and inner ease', scoreValue: 5 },
    ],
  },
  {
    id: 'q2_stress',
    dimension: 'stress',
    aggregateDimension: 'stress_regulation',
    categoryName: 'Stress & Demand',
    title: 'How often have you felt overwhelmed by the responsibilities you need to manage?',
    description: 'Think about work, personal obligations, decisions, and unexpected pressures.',
    reverseScored: true, // Higher option index = higher stress, so scoreValue is inverted for wellness calculation
    options: [
      { id: 'st1', label: 'Rarely or never', sublabel: 'Demands feel very manageable and paced', scoreValue: 5 },
      { id: 'st2', label: 'Occasionally', sublabel: 'Mild pressure at times, but quickly resolved', scoreValue: 4 },
      { id: 'st3', label: 'Sometimes', sublabel: 'Noticeable strain during busier days', scoreValue: 3 },
      { id: 'st4', label: 'Often', sublabel: 'Frequently stretched thin or rushing to keep up', scoreValue: 2 },
      { id: 'st5', label: 'Almost constantly', sublabel: 'Feeling buried under ongoing demands', scoreValue: 1 },
    ],
  },
  {
    id: 'q3_anxiety',
    dimension: 'anxiety',
    aggregateDimension: 'stress_regulation',
    categoryName: 'Inner Calm & Relaxation',
    title: 'How often have you found it difficult to relax, quiet your mind, or switch off?',
    description: 'Consider physical restlessness, racing thoughts, or difficulty unwinding in downtime.',
    reverseScored: true,
    options: [
      { id: 'ax1', label: 'Almost never', sublabel: 'Able to disconnect and unwind naturally', scoreValue: 5 },
      { id: 'ax2', label: 'Occasionally', sublabel: 'Slight restlessness, easily settled with rest', scoreValue: 4 },
      { id: 'ax3', label: 'Sometimes', sublabel: 'Mind stays busy or tense after busy days', scoreValue: 3 },
      { id: 'ax4', label: 'Often', sublabel: 'Persistent tension or recurring thoughts', scoreValue: 2 },
      { id: 'ax5', label: 'Very frequently', sublabel: 'Hard to find any moments of true stillness', scoreValue: 1 },
    ],
  },
  {
    id: 'q4_sleep',
    dimension: 'sleep',
    aggregateDimension: 'sleep_energy',
    categoryName: 'Sleep & Restoration',
    title: 'How would you describe the quality and restfulness of your recent sleep?',
    description: 'Consider ease of falling asleep, waking up through the night, and morning refreshed feeling.',
    reverseScored: false,
    options: [
      { id: 'sl1', label: 'Severely disrupted or sparse', sublabel: 'Consistently waking unrefreshed or exhausted', scoreValue: 1 },
      { id: 'sl2', label: 'Inconsistent and light', sublabel: 'Frequent awakenings or restless periods', scoreValue: 2 },
      { id: 'sl3', label: 'Adequate, with room to improve', sublabel: 'Fair rest, though some mornings feel slow', scoreValue: 3 },
      { id: 'sl4', label: 'Good and restorative', sublabel: 'Mostly solid sleep; waking up refreshed', scoreValue: 4 },
      { id: 'sl5', label: 'Deep, sound, and rejuvenating', sublabel: 'Consistent, restful, nourishing sleep', scoreValue: 5 },
    ],
  },
  {
    id: 'q5_energy',
    dimension: 'energy',
    aggregateDimension: 'sleep_energy',
    categoryName: 'Energy & Vitality',
    title: 'How has your physical energy and stamina felt throughout everyday activities?',
    description: 'Notice your motivation to move, physical resilience, and daytime alertness.',
    reverseScored: false,
    options: [
      { id: 'en1', label: 'Depleted', sublabel: 'Even basic physical tasks take deliberate effort', scoreValue: 1 },
      { id: 'en2', label: 'Frequently sluggish', sublabel: 'Hitting frequent mid-day fatigue walls', scoreValue: 2 },
      { id: 'en3', label: 'Moderate', sublabel: 'Sufficient energy for routine chores and tasks', scoreValue: 3 },
      { id: 'en4', label: 'Consistently steady', sublabel: 'Reliable endurance throughout normal days', scoreValue: 4 },
      { id: 'en5', label: 'Vibrant and resilient', sublabel: 'Feeling active, energized, and capable', scoreValue: 5 },
    ],
  },
  {
    id: 'q6_focus',
    dimension: 'focus',
    aggregateDimension: 'focus_functioning',
    categoryName: 'Focus & Mental Clarity',
    title: 'How easy has it been to maintain concentration on your daily tasks or studies?',
    description: 'Notice reading comprehension, following conversations, and staying with one activity.',
    reverseScored: false,
    options: [
      { id: 'fc1', label: 'Very difficult', sublabel: 'Easily pulled away; mental fog persists', scoreValue: 1 },
      { id: 'fc2', label: 'Harder than usual', sublabel: 'Frequently re-reading or restarting tasks', scoreValue: 2 },
      { id: 'fc3', label: 'Moderate', sublabel: 'Normal focus with standard distractions', scoreValue: 3 },
      { id: 'fc4', label: 'Good clarity', sublabel: 'Can sustain attention on priorities with ease', scoreValue: 4 },
      { id: 'fc5', label: 'Sharp and immersed', sublabel: 'Deep focus, clear thinking, and flow state', scoreValue: 5 },
    ],
  },
  {
    id: 'q7_social',
    dimension: 'social',
    aggregateDimension: 'social_wellbeing',
    categoryName: 'Social Connection & Belonging',
    title: 'How connected and supported have you felt in relationships with people around you?',
    description: 'Think of friends, family, peers, or community members you can confide in or share moments with.',
    reverseScored: false,
    options: [
      { id: 'sc1', label: 'Isolated or disconnected', sublabel: 'Feeling distant without meaningful outlets', scoreValue: 1 },
      { id: 'sc2', label: 'Somewhat detached', sublabel: 'Surface interactions, lacking closeness', scoreValue: 2 },
      { id: 'sc3', label: 'Moderately connected', sublabel: 'A few trusted touchpoints when needed', scoreValue: 3 },
      { id: 'sc4', label: 'Well supported', sublabel: 'Meaningful mutual check-ins and shared laughs', scoreValue: 4 },
      { id: 'sc5', label: 'Deeply bonded and understood', sublabel: 'Strong belonging, warmth, and reliable trust', scoreValue: 5 },
    ],
  },
  {
    id: 'q8_functioning',
    dimension: 'functioning',
    aggregateDimension: 'focus_functioning',
    categoryName: 'Everyday Functioning',
    title: 'How much have your recent emotions or stress affected your daily routines and plans?',
    description: 'Consider meals, personal care, hobbies, obligations, and following through on intentions.',
    reverseScored: true, // Higher effect = more friction, so reverse scored
    options: [
      { id: 'fn1', label: 'Not at all', sublabel: 'Routines and plans proceed seamlessly', scoreValue: 5 },
      { id: 'fn2', label: 'Minimal friction', sublabel: 'Occasional minor delay, easily handled', scoreValue: 4 },
      { id: 'fn3', label: 'Some noticeable impact', sublabel: 'Certain tasks put off or feel heavier', scoreValue: 3 },
      { id: 'fn4', label: 'Significant disruption', sublabel: 'Skipping essential routines or obligations', scoreValue: 2 },
      { id: 'fn5', label: 'Substantial disruption', sublabel: 'Very hard to sustain regular everyday routines', scoreValue: 1 },
    ],
  },
];
